FROM python:2.7

ENV BUILD_HTTPS_PROXY='something'
ENV BUILD_HTTP_PROXY='something'

ENV HTTP_PROXY=$BUILD_HTTP_PROXY
ENV HTTPS_PROXY=$BUILD_HTTPS_PROXY

COPY ./ /src
WORKDIR /src
RUN echo "HTTP_PROXY is " $HTTP_PROXY
RUN echo $HTTP_PROXY

EXPOSE  8080

CMD ["python", "app.py"]



